services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/Rentals-root:/app
      - db-data:/app/db.sqlite3.d
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

volumes:
  db-data:
