# Generated by Django 6.0.2 on 2026-03-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMMUTER', 'Commuter'), ('PROVIDER', 'Mobility Provider'), ('ADMIN', 'City Admin')], default='COMMUTER', max_length=10),
        ),
    ]
