# Generated by Django 6.0.2 on 2026-03-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_role_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_city',
            field=models.CharField(blank=True, choices=[('MTL', 'Montreal'), ('LAV', 'Laval'), ('LON', 'Longueuil'), ('QC', 'Quebec City'), ('GAT', 'Gatineau'), ('SHE', 'Sherbrooke')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_mobility_type',
            field=models.CharField(blank=True, choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter')], default='', max_length=10),
        ),
    ]
