# Generated by Django 6.0.2 on 2026-02-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasoline'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('DIESEL', 'Diesel')], max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('total_trips', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['make', 'model'], name='booking_car_make_ff7713_idx'), models.Index(fields=['daily_rate'], name='booking_car_daily_r_54dad1_idx')],
            },
        ),
    ]
