# Generated by Django 6.0.2 on 2026-03-24 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_kind', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter')], max_length=10)),
                ('vehicle_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=15)),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('total_trips', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.vehicle')),
                ('bike_type', models.CharField(choices=[('STANDARD', 'Standard'), ('EBIKE', 'E-Bike')], default='STANDARD', max_length=10)),
                ('has_motor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bike',
            },
            bases=('booking.vehicle',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.vehicle')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasoline'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('DIESEL', 'Diesel')], max_length=20)),
                ('body_style', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Car',
            },
            bases=('booking.vehicle',),
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.vehicle')),
                ('engine_cc', models.PositiveIntegerField(default=50)),
                ('is_electric', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Scooter',
            },
            bases=('booking.vehicle',),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model'], name='booking_veh_make_9996eb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['daily_rate'], name='booking_veh_daily_r_b1c46d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_kind'], name='booking_veh_vehicle_b8fb91_idx'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.vehicle'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['vehicle', 'start_date', 'end_date'], name='booking_res_vehicle_e41e08_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='booking_res_user_id_e82983_idx'),
        ),
    ]
