# Generated by Django 6.0.2 on 2026-03-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_add_owner_to_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pricing_strategy',
            field=models.CharField(choices=[('STANDARD', 'Standard Rate'), ('WEEKEND', 'Weekend Rate'), ('SURGE', 'Surge Pricing')], default='STANDARD', max_length=10),
        ),
    ]
