# Generated by Django 6.0.2 on 2026-03-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_notification_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.CharField(choices=[('MTL', 'Montreal'), ('LAV', 'Laval'), ('LON', 'Longueuil'), ('QC', 'Quebec City'), ('GAT', 'Gatineau'), ('SHE', 'Sherbrooke')], default='MTL', max_length=5),
        ),
    ]
